"use strict";

var CONFIG_OPTIONS = {
  CONFIG_LANGUAGES: [
    ["en-us", "English"],
    ["de-de", "Deutsch"],
    ["fr-fr", "Français"],
    ["ja-jp", "日本語"],
    ["ko-kr", "한국인"],
    ["ru-ru", "Русский"],
    ["zh-cn", "简体中文"],
    ["zh-tw", "繁體中文"],
  ],
  CONFIG_VERSIONS: [
    ["master",    "master"],
    ["latest",    "latest"],
    ["stable",    "stable"],
    ["newline",   "newline"],       /* Newline */
    ["4.5",       "4.5"],
    ["4.4",       "4.4"],
    ["4.3",       "4.3"],
    ["4.2",       "4.2"],
    ["4.1",       "4.1"],
    ["4.0",       "4.0"],
    ["newline",   "newline"],       /* Newline */
    ["rolling",   "Rolling (dev)"],
    ["jazzy",     "Jazzy (latest)"],
    ["iron",      "Iron (EOL)"],
    ["humble",    "Humble"],
    ["galactic",  "Galactic (EOL)"],
    ["foxy",      "Foxy (EOL)"],
    ["eloquent",  "Eloquent (EOL)"],
    ["dashing",   "Dashing (EOL)"],
    ["crystal",   "Crystal (EOL)"],
    ["newline",   "newline"],       /* Newline */
    ["3.9",       "3.9"],
    ["3.8",       "3.8"],
    ["3.7",       "3.7"],
    ["3.6",       "3.6"],
    ["3.5",       "3.5"],
    ["3.4",       "3.4"],
    ["3.3",       "3.3"],
    ["3.2",       "3.2"],
    ["3.1",       "3.1"],
    ["3.0",       "3.0"],
    ["newline",   "newline"],       /* Newline */
    ["2.13",      "2.13"],
    ["2.12",      "2.12"],
    ["2.11",      "2.11"],
    ["2.10",      "2.10"],
    ["2.9",       "2.9"],
    ["2.8",       "2.8"],
    ["2.7",       "2.7"],
    ["2.6",       "2.6"],
    ["2.5",       "2.5"],
    ["2.4",       "2.4"],
    ["2.3",       "2.3"],
    ["2.2",       "2.2"],
    ["2.1",       "2.1"],
    ["2.0",       "2.0"],
  ],
  CONFIG_PROJECTS: [
    ["Home",    "https://www.ltdorgtest.org"],
    ["Crowdin", "https://ltdorgtest.crowdin.com/demo-docs-l10n"],
    ["GitHub",  "https://github.com/ltdorgtest/demo-docs-l10n"],
    ["GitCode", "https://gitcode.com/ltdorgtest/demo-docs-l10n"],
    ["GitFlic", "https://gitflic.ru/project/ltdorgtest/demo-docs-l10n"],
  ]
};
